language: c
script: ./configure ${CONFIG_OPTS} && make W=1
dist: trusty
compiler: gcc

matrix:
  include:
    - os: linux

    - os: linux
      addons:
        apt:
          packages:
            - gcc-mingw-w64-x86-64
            - mingw-w64-x86-64-dev
      env:
        - CONFIG_OPTS="--host x86_64-w64-mingw32"

    - os: linux
      addons:
        apt:
          packages:
            - gcc-mingw-w64-i686
            - mingw-w64-i686-dev
      env:
        - CONFIG_OPTS="--host i686-w64-mingw32"

before_install:
    - eval "${MATRIX_EVAL}"


notifications:
  email:
    recipients:
      - logang@deltatee.com
